name: Customizing GitHub Actions Workflow
on:
  push:
    branches:
      - development
      - staging
      - production
env:
 ENV: ${{ github.ref_name }}
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Set up JDK 15
        uses: actions/setup-java@v4
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build
        run: gradle build
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: '**/build/libs/'
          run: chmod +x '**/build/libs/'
  production:
    if: ${{ github.ref_name == 'production' }}
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    environment: production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Run application
        run: |
          java -jar '${{ github.workspace }}/build/libs/multiple-env-1.0-SNAPSHOT.jar'
  staging:
    if: ${{ github.ref_name == 'staging' }}
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    environment: staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Run application
        run: |
          java -jar '${{ github.workspace }}/build/libs/multiple-env-1.0-SNAPSHOT.jar'
  development:
    if: ${{ github.ref_name == 'development' }}
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    environment: development
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Run application
        run: |
          java -jar '${{ github.workspace }}/build/libs/multiple-env-1.0-SNAPSHOT.jar'
